# Generated by Django 4.0.6 on 2022-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=20)),
            ],
        ),
    ]
